image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

before_script:
  - chmod a+x ./mvnw

build:
  stage: build
  script:
    - docker build -t vinaykumar6/reactive-web-demo-aws .
    
test:
  stage: test
  script:
    - docker build -t vinaykumar6/reactive-web-demo-aws-test -f Dockerfile.dev .
    
release:
  stage: release
  script:
    - echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin
    - docker push vinaykumar6/reactive-web-demo-aws
  only:
    - master