image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

before_script:
  - chmod a+x ./mvnw
  - echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin
 
build:
  stage: build
  script:
    - docker build -t vinaykumar6/reactive-web-demo-aws .
    - docker push vinaykumar6/reactive-web-demo-aws

test:
  stage: test
  script:
    - ./mvnw install
    
release:
  stage: release
  script:
    - docker pull vinaykumar6/reactive-web-demo-aws
  only:
    - master