version: '3.7'
services:
  mongo-db:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
  reactive-server:
    build: .
    ports:
      - "8080:8080"
volumes:
  mongodb_data_container:
    