FROM openjdk:8-jdk-alpine as build
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw spring-boot:run -Dspring-boot.run.profiles=test
ENTRYPOINT ["echo", "Test Executed"]