spring:
  profiles:    active: test---
spring:  profiles: docker
  data.mongodb:
    host: mongo-cluster-ip-service
    port: 27017    database: local
  
---
spring:
  profiles: dev
  data.mongodb:
    host: localhost
    port: 27017
    database: local
  
---
spring:
  profiles: prod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
    
---

spring:
  profiles: test
 